### ISSUE TITLE
Make second-section responsive

### ISSUE THREAD

**Issue by alengusinac** [Medieinstitutet/fed22d-grafiska-verktyg-arrabiatan#20]

**Comment by KennedyB1** [comment]
![desktop](https://user-images.githubusercontent.com/114904314/213034345-faad2a8e-bd0f-4623-b1a7-2a0cbcf0bc35.png)
![tablet](https://user-images.githubusercontent.com/114904314/213034349-387938aa-ceb4-480c-a6bb-e61e80c137bc.PNG)
